### ISSUE TITLE
Add Linked List creation program

### ISSUE THREAD

**Issue by YuktaG123** [Sujal-2820/Hacktoberfest-DSA#4]
Hey @Sujal-2820 ,

I would like to add a code for creating linked list in the repository.

Can you assign me the issue and label it as "Hacktoberfest - accepted".

**Comment by Sujal-2820** [comment]
Hey @YuktaG123,

I would assign you the issue. Please go ahead with your contribution.

**Comment by Sujal-2820** [comment]
Also make sure to add your contributing information inside the "contributors" file in the same format as the first one.
